name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Type check
        run: bun run check

      - name: Lint
        run: bun run lint

      - name: Run tests
        run: bun run test
        env:
          VITE_SUPABASE_URL: https://test-project.supabase.co
          VITE_SUPABASE_ANON_KEY: test_key

      - name: Build
        run: bun run build
